### ISSUE TITLE
missing .gitignore file

### ISSUE THREAD

**Issue by jeras** [cdsgit/cdsgit#11]
There is no filter regarding which files should or should not be versioned.
For example cell lock files should not be added to git while adding the entire cell.
The same goes for temporary files ending with %.

**Comment by cookacounty** [comment]
In the setup directory, there is a gitignore. I added this to the README.

https://github.com/cdsgit/cdsgit/blob/master/setup/cadence.gitignore

If you have anything to add please submit a PR

**Comment by jeras** [comment]
OK, I will have to try again, I am not sure why it added a cell lock file.
