### ISSUE TITLE
inconsistent termination of the path 

### ISSUE THREAD

**Issue by williamsi350** [cdsgit/cdsgit#3]
some lines expect the CDSGIT_PATH variable to have a / at the end, some don't. 
changes & pull request made.

Also may be better to advise that people edit their .cdsinit_personal or .cdsinit_local file instead of .cdsinit. (personal worked for me, local may be buggy in systems with IC5 and IC6 installed)

Would be nice if you could clarify what is working and not working. Setting a remote doesn't seem to work using the menu options, but i think running the git command in a terminal does. Will running a mixture of cdsgit commands from cadence and terminal commands  cause issues?

**Comment by cookacounty** [comment]
Thanks for the MR on the path, I guess I wasn't as consistent with that as I thought :smiley: 

As far as the .cdsinit goes, I would have to look at the Cadence docs. ".cdsinit_local" sounds like something custom your company may be loading. From what I remember the Cadence standard is to load the .cdsinit in the install, then your home, then the working directory.

On your last point: You will notice all of the verbose info in your CIW from the git commands being executed, there is not difference between running a command from the cdsgit menus vs. from a shell. 

I thought I had everything working except for the diff tools so if there is something broken or missing please create an issue and I will get it added!

**Comment by cookacounty** [comment]
And by MR (merge request) I meant pull request.
