### ISSUE TITLE
problems with Commit function

### ISSUE THREAD

**Issue by caduser2k** [cdsgit/cdsgit#8]
Hi, Aaron.

O started using your CdsGit and followed the example in the documentation but, when I tried to make a commit, I got the following error message:

_Error_ FullPath: too few arguments (2 expected, 1 given) - (stdobj@0x1dea7ef0)
<<< Stack Trace >>>
FullPath(gsp)
(fullPath = (FullPath gsp))
if((gsp->gs) then (fullPath = (FullPath gsp)) let((lib) foreach(lib (&->libList) if(& then &))) else ... )
GetLib(gsp)
foreach(line response_list if((gs->verbose) printf("%s\n" line)) (regexp = "^[ MADRCU?]+[ MADRCUT?]+[ ]+") (matched = rexMatchp(regexp line)) ... )
let((line) foreach(line response_list if((gs->verbose) printf("%s\n" line)) (regexp = "^[ MADRCU?]+[ MADRCUT?]+[ ]+") (matched = rexMatchp(regexp line)) ... ))
if((response == "") then if(showInfo then Info(gs sprintf(nil "Path %s is clean" &))) (gs->clean = t) else ... )
Status(gs)
CGstatusForm(gs)
case(_menuName ("CGMgui" Gui(gs)) ("CGMinit" CGPBinitForm()) ("CGMstatusAll" CGstatusAllForm()) ("CGMclone" CGcloneForm()) ... )
...

could you help me?

thanks,

best regards,

Noel Carneiro

**Comment by cookacounty** [comment]
@caduser2k Is this still an issue? I'm going to need a bit more info to clean this up.
